
###
GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "nationalId": "41094390",
  "email": "mukirisimon22@gmail.com",
  "firstname": "Simon",
  "middlename": "Njoroge",
  "lastname": "Mukiri",
  "username": "simon",
  "phoneNumber": "0701234693",
  "location": "Nairobi"
}
