

services:
  postgres:
    image: postgres:13-alpine
    container_name: rental_postgres
    environment:
      - NODE_ENV=development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rental_network

    env_file:
      - .env

  redis:
    image: redis:6-alpine
    container_name: rental_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rental_network

  app:
    build: .
    container_name: rental_app
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - rental_network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  rental_network:
    driver: bridge